### ISSUE TITLE
Can TWAS analysis be performed on plant samples using MTWAS? 

### ISSUE THREAD

**Issue by WenChangYu** [szcf-weiya/MTWAS#2]
Dear developer,

We would like to perform TWAS analysis on a plant population. Our data consists of phenotypes, whole-genome gene expression levels, and genotypes for each sample.

We do not have a reference dataset.

Would our data be suitable for analysis with MTWAS?

many thanks,

Chunyang

**Comment by shuangsong0110** [comment]
Dear Chunyang,

Thank you for your question. In theory, it is possible to train TWAS weights using the functions described in the 'Train your own weights' section. However, we have not tested this method on plants, so its performance in that context cannot be guaranteed.


Best,

Shuang

**Comment by WenChangYu** [comment]
Thanks for your kindly reply.

**Comment by Dece1212** [comment]
Dear Developer, 
why does the transcriptome dataset(demo[["E"]][["Adipose_Subcutaneous"]]) in your MTWAS test dataset contain negative values? Has it been transformed?
Thank you very much，
Dece

**Comment by shuangsong0110** [comment]
> Dear Developer, why does the transcriptome dataset(demo[["E"]][["Adipose_Subcutaneous"]]) in your MTWAS test dataset contain negative values? Has it been transformed? Thank you very much， Dece

Hi Dece,

Yes, the expression values were normalized through rank-based inverse normal transformation, and were further adjusted for sex, 3 genotyping PCs, and top 15 PEER factors. Please see the "Data processing" section in our paper for more details.

Best,
Shuang

**Comment by Dece1212** [comment]
> > Dear Developer, why does the transcriptome dataset(demo[["E"]][["Adipose_Subcutaneous"]]) in your MTWAS test dataset contain negative values? Has it been transformed? Thank you very much， Dece尊敬的开发人员，为什么 MTWAS 测试数据集中的转录组数据集（demo[[“E”]][[“Adipose_Subcutaneous”]]） 包含负值？它已经改变了吗？非常感谢你，Dece
> 
> Hi Dece,嗨，Dece，
> 
> Yes, the expression values were normalized through rank-based inverse normal transformation, and were further adjusted for sex, 3 genotyping PCs, and top 15 PEER factors. Please see the "Data processing" section in our paper for more details.是的，通过基于秩的逆正态变换对表达值进行归一化，并针对性别、3 个基因分型 PC 和前 15 个 PEER 因子进一步调整。有关更多详细信息，请参阅我们论文中的“数据处理”部分。
> 
> Best,最好 Shuang双

Thanks for ur reply! I will be check it carefully.

**Comment by Dece1212** [comment]
> > Dear Developer, why does the transcriptome dataset(demo[["E"]][["Adipose_Subcutaneous"]]) in your MTWAS test dataset contain negative values? Has it been transformed? Thank you very much， Dece
> 
> Hi Dece,
> 
> Yes, the expression values were normalized through rank-based inverse normal transformation, and were further adjusted for sex, 3 genotyping PCs, and top 15 PEER factors. Please see the "Data processing" section in our paper for more details.
> 
> Best, Shuang

Thanks for ur reply! I will be check it carefully.
